Added Game List to client
CS-340-Dream-Team/ticket-to-ride-frontend pull request #3
Opened 2018-09-29 19:11 UTC by bandrus5

2018-10-01 15:09 UTC, drewctate commented
This is awesome work, @bandrus5! Just check those new tests using `yarn test`.

2018-10-01 15:10 UTC, drewdaemon requested changes
This is awesome work, @bandrus5! Just check those new tests using yarn test.

2018-10-01 15:10 UTC, drewctate commented on src/app/game-list-manager.service.spec.ts
> +import { GameListManagerService } from './game-list-manager.service';
Looks like this import is failing. Use `yarn test` to see what I mean.

2018-10-01 15:17 UTC, drewdaemon requested changes
We should talk a little about how to handle types. I set it up to use a bucket file and exported interfaces with a the following naming convention: `<type>.type.ts`. It looks like you're using capitalized classes. That's dope, but we just probably need to get on the same page 😄

2018-10-01 15:17 UTC, drewctate commented on src/app/game-list/game-list.component.ts
> +import { Game } from '../types/game/Game';
Nice job adding types! Let's add all types to the `types/index.ts` file so that external imports can be from just `types/`

2018-10-01 15:19 UTC, drewctate commented on src/app/services/index.ts
> +export * from './game-list-manager/game-list-manager.service';
Awesome job! Let's keep these in alphabetical order!

2018-10-03 22:31 UTC, drewdaemon approved these changes

2018-10-03 22:32 UTC, merged